// Package spec provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package spec

// GenerateReportRequest defines model for GenerateReportRequest.
type GenerateReportRequest struct {
	DateFrom int64 `json:"date_from"`
	DateTill int64 `json:"date_till"`
}

// GenerateReportResponse defines model for GenerateReportResponse.
type GenerateReportResponse struct {
	Link string `json:"link"`
}

// PostGenerateReportJSONBody defines parameters for PostGenerateReport.
type PostGenerateReportJSONBody = GenerateReportRequest

// PostGenerateReportJSONRequestBody defines body for PostGenerateReport for application/json ContentType.
type PostGenerateReportJSONRequestBody = PostGenerateReportJSONBody
